pull_request_rules:

- name: Automatically approve Scala Steward PRs
  conditions: &base_merge_conditions
  - author=horothesun-scala-steward[bot]
  - status-success=unit-tests
  - status-success=integration-tests
  - status-success=shellcheck
  - status-success=lint
  actions:
    review:
      type: APPROVE

- name: Automatically merge Scala Steward PRs
  conditions:
  - and: *base_merge_conditions
  - and:
    - "#approved-reviews-by>=1"
  actions:
    merge:
      method: squash
