name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: |
        ./scripts/test_db_up.sh
        sbt test
        ./scripts/test_db_down.sh

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        check_together: yes
        scandir: './scripts'
      env:
        SHELLCHECK_OPTS: --severity style --enable all --exclude SC2312 --shell bash

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: sbt scalafmtSbtCheck scalafmtCheck Test/scalafmtCheck
